ASM code for Minor Extended Sprites implementation
JackTheSpades/SpriteToolSuperDelux pull request #43
Opened 2021-06-07 17:32 UTC by TheLX5

Seems to work flawlessly. Check SnesLab's PIXI channel for test cases.

2021-06-07 17:34 UTC, TheLX5 commented
Actually, I forgot I can submit files here lol. Here you go.

[minorextended_test.zip](https://github.com/JackTheSpades/SpriteToolSuperDelux/files/6610967/minorextended_test.zip)

2021-06-07 22:21 UTC, Atari2 commented on routines/SpawnMinorExtended.asm
> +    ;bne ?.ret
Semicolon should not be here, pls fix

2021-06-07 22:22 UTC, Atari2 requested changes

2021-06-07 22:22 UTC, Atari2 commented on routines/SpawnMinorExtended.asm
> +    ;bne ?.ret
Semicolon should be removed.

2021-07-04 07:37 UTC, TheLX5 commented
No longer relevant as it's contained in https://github.com/JackTheSpades/SpriteToolSuperDelux/pull/44

2021-07-04 07:37 UTC, closed without merging